---
- name: create /lib/security directory if it doesn't exist
  file:
    path: /lib/security
    state: directory
  when: ansible_os_family == 'Debian'

- name: get the latest release info from github
  ansible.builtin.uri:
    url: https://api.github.com/repos/outerbounds/pam-jwt/releases/latest
    return_content: true
  register: json_response

- name: download pam_jwt.so file
  get_url:
    url: "{{ json_response.json.assets.0.browser_download_url }}"
    dest: /lib/security/pam_jwt.so
    mode: '0644'
  check_mode: false

- name: add outerbounds PAM configuration
  ansible.builtin.template:
    src: sshd.tmpl
    dest: /etc/pam.d/sshd
    mode: '0644'
    backup: true
  when: ansible_os_family == 'Debian'
  notify: restart_ssh_service

- name: enable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication no$"
    line: "PasswordAuthentication yes"
    backup: true
    backrefs: true
  when: ansible_os_family == 'Debian'
